language: android

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-23.0.3
    - android-24

    # Support library
    - extra-android-support
    - extra-android-m2repository

script:
    - chmod +x ./gradlew
